substitutions:
  shelly_id: "Dinner Table"
  device_name: Shelly ${shelly_id}
  espname: "shelly-dinnertable"

  #STM_firmware_version: "51.7"
  shelly_dimmer_version: "Shelly Dimmer 2"
  #input_pin: GPIO14

  max_power: "220.0" # watt
  max_temp: "70.0" # Â°C
  max_brightness: "1000"
  min_brightness: "50"
  gamma_correct: "2"
  warmup_brightness: "0"

  ntc_b_constant: "3350"
  ntc_reference_resistance: "10kOhm"
  ntc_reference_temperature: "298.15K"

packages:
  shelly: !include
    file: templates/shelly_dimmer.yaml
    vars:
      max_brightness: ${max_brightness}
      min_brightness: ${min_brightness}
      gamma_correct: ${gamma_correct}
      warmup_brightness: ${warmup_brightness}

wifi:
  use_address: 10.0.30.179
