substitutions:
  shelly_id: "Closet"
  device_name: "Shelly ${shelly_id}"
  espname: "shelly-closet"
  STM_firmware_version: "51.6"
  shelly_dimmer_version: "Shelly Dimmer 1"
  input_pin: GPIO12

  max_power: "220.0" # watt
  max_temp: "70.0" # Â°C
  max_brightness: "1000"
  min_brightness: "40"

  ntc_b_constant: "3350"
  ntc_reference_resistance: "10kOhm"
  ntc_reference_temperature: "298.15K"

<<: !include templates/shelly_dimmer.yaml
