substitutions:
  shelly_id: "Baby Room"
  device_name: Shelly ${shelly_id}
  espname: "shelly-babyroom"

  ntc_b_constant: "3350"
  ntc_reference_resistance: "10kOhm"
  ntc_reference_temperature: "298.15K"

  relay_restore_mode: "ALWAYS_ON"
  detached_mode_restore_mode: "RESTORE_DEFAULT_ON"

<<: !include templates/shelly_1_plus_mini.yaml
