substitutions:
  shelly_id: "Bathroom"
  device_name: Shelly ${shelly_id}
  espname: shelly-bathroom-new
  channel_1: Mirror Light
  channel_2: Spotlights
  max_power: "2000.0" # watt
  max_temp: "80.0" # Â°C

<<: !include templates/shelly_plus_2_pm.yaml
